package jatf.api.constraints;

public enum Constraint {
    SCOPES,
    ROOT_FOLDER,
    INSTABILITY_STRICT,
    INSTABILITY_LOOSE,
    MAXIMUM_CCN,
    MAX_HALSTEAD_DELIVERED_BUGS,
    MAX_NUMBER_OF_METHODS_PER_CLASS,
    MAX_NUMBER_OF_STATEMENTS_PER_METHOD,
    MAX_DEPTH_FOR_DFS,
    MIN_DEGREE_OF_PURITY,
    MAX_CHAINED_METHOD_CALLS
}
